name: Deploy Telegram Bot

on:
  push:
    branches:
      - main  # This triggers the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specify the environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the version of Python to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      - name: Run Telegram Bot
        env:
          TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Access the secret token
        run: python bot.py  # Run your main bot script